apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    application: backend
spec:
  replicas: 4
  selector:
    matchLabels:
      application: backend
  template:
    metadata:
      labels:
        application: backend
    spec:
      containers:
      - name: nginx
        image: nginx
