apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: activity-local-claim
spec:
  storageClassName: activity-local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
