apiVersion: apps/v1
kind: Deployment
metadata:
  name: pageview-deployment
  labels:
    app: pageview-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pageview
  template:
    metadata:
      labels:
        app: pageview
    spec:
      containers:
      - name: pageview
        image: mtheunissen82/pageview:latest
        env:
        - name: APP_PORT
          value: "8080"
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        ports:
        - containerPort: 8080
